batch_size: 32
columns_names:
- L_Up_Acc_X
- L_Up_Acc_Y
- L_Up_Acc_Z
- L_Up_Gyr_X
- L_Up_Gyr_Y
- L_Up_Gyr_Z
- L_Lower_Acc_X
- L_Lower_Acc_Y
- L_Lower_Acc_Z
- L_Lower_Gyr_X
- L_Lower_Gyr_Y
- L_Lower_Gyr_Z
- R_Up_Acc_X
- R_Up_Acc_Y
- R_Up_Acc_Z
- R_Up_Gyr_X
- R_Up_Gyr_Y
- R_Up_Gyr_Z
- R_Lower_Acc_X
- R_Lower_Acc_Y
- R_Lower_Acc_Z
- R_Lower_Gyr_X
- R_Lower_Gyr_Y
- R_Lower_Gyr_Z
- L_IE
- L_AA
- L_FE
- R_IE
- R_AA
- R_FE
cost_threashold: 0.001
device: cuda
epochs: 100
features_names:
- L_Up_Acc_X
- L_Up_Acc_Y
- L_Up_Acc_Z
- L_Up_Gyr_X
- L_Up_Gyr_Y
- L_Up_Gyr_Z
- L_Lower_Acc_X
- L_Lower_Acc_Y
- L_Lower_Acc_Z
- L_Lower_Gyr_X
- L_Lower_Gyr_Y
- L_Lower_Gyr_Z
- R_Up_Acc_X
- R_Up_Acc_Y
- R_Up_Acc_Z
- R_Up_Gyr_X
- R_Up_Gyr_Y
- R_Up_Gyr_Z
- R_Lower_Acc_X
- R_Lower_Acc_Y
- R_Lower_Acc_Z
- R_Lower_Gyr_X
- R_Lower_Gyr_Y
- R_Lower_Gyr_Z
features_num: 24
labels_names:
- L_IE
- L_AA
- L_FE
- R_IE
- R_AA
- R_FE
labels_num: 6
learning_rate: 0.1
norm_type: mean_std
raw_dataset_path: ./datasets_files/raw_datasets.hdf5
raw_datasets_path: ./datasets_files/raw_datasets.hdf5
sub_idx:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
test_sub_idx:
- '0'
train_sub_idx:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
window_size: 10
